name: Build

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: "18.04"
            repository: "caddy-script-18-hello-world"
            feature: "HelloWorld"
          - file: "18.04"
            repository: "caddy-script-18-wordpress"
            feature: "WordPress"
          - file: "20.04"
            repository: "caddy-script-20-hello-world"
            feature: "HelloWorld"
          - file: "20.04"
            repository: "caddy-script-20-wordpress"
            feature: "WordPress"
    steps:
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfiles/${{ matrix.file }}
          repository: ${{ matrix.repository }}
          push: false
      - name: Docker Run
        id: docker_run
        uses: addnab/docker-run-action@v1
        with:
          image: ${{ matrix.repository }}:latest
          run: /bin/bash -c "export GITHUB_ACTIONS=1; export FEATURE=${{ matrix.feature }}; apt-get update; apt-get install -y curl sudo software-properties-common; bash main.sh"
