name: Build

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: "18.04"
            feature: "hello-world"
          - file: "18.04"
            feature: "wordpress"
          - file: "20.04"
            feature: "hello-world"
          - file: "20.04"
            feature: "wordpress"
    steps:
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfiles/${{ matrix.file }}
          tags: caddy-script-${{ matrix.file }}-${{ matrix.feature }}
          push: false
      - name: Docker Run
        id: docker_run
        uses: addnab/docker-run-action@v3
        with:
          image: caddy-script-${{ matrix.file }}-${{ matrix.feature }}:latest
          run: /bin/bash -c "export GITHUB_ACTIONS=1; export FEATURE=${{ matrix.feature }}; apt-get update; apt-get install -y curl sudo software-properties-common; bash main.sh"
